version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.16.0-browsers

jobs:
  Run:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Node
          command: node index.js

workflows:
  version: 2
  test-deploy:
    jobs:
      - Run