name: Trigger Site Rebuild on a CRON Scheduleon:

  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '* * * * *'

jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: node index.js